name: bae
options:
  bundleIdPrefix: fm.bae
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
targets:
  bae:
    type: application
    platform: macOS
    sources:
      - bae
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: fm.bae.macos
        PRODUCT_NAME: bae
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.10"
