name: 'Setup Linux Build Environment'
description: 'Install Linux dependencies and configure environment for building bae'

inputs:
  ffmpeg-version:
    description: 'bae-ffmpeg release tag'
    required: false
    default: 'v8.0.1-bae3'

runs:
  using: 'composite'
  steps:
    - name: Install Linux dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          patchelf \
          libxdo-dev \
          libasound2-dev \
          libdiscid-dev \
          libcdio-dev \
          libiso9660-dev \
          libudf-dev \
          libsodium-dev \
          pkg-config \
          libtorrent-rasterbar-dev \
          libboost-all-dev \
          pulseaudio

    - name: Download bae-ffmpeg
      shell: bash
      run: |
        ARCH=$(uname -m)
        FFMPEG_DIR=/opt/bae-ffmpeg
        sudo mkdir -p "$FFMPEG_DIR"
        curl -L "https://github.com/bae-fm/bae-ffmpeg/releases/download/${{ inputs.ffmpeg-version }}/ffmpeg-linux-$ARCH.tar.gz" | \
          sudo tar xz -C "$FFMPEG_DIR"
        echo "FFMPEG_DIR=$FFMPEG_DIR" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$FFMPEG_DIR/lib/pkgconfig" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$FFMPEG_DIR/lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$FFMPEG_DIR/lib" >> $GITHUB_ENV
        echo "$FFMPEG_DIR/bin" >> $GITHUB_PATH

    - name: Start virtual audio device
      shell: bash
      run: |
        pulseaudio --start --exit-idle-time=-1
        pactl load-module module-null-sink sink_name=DummyOutput sink_properties=device.description="Virtual_Output"
