name: 'Setup Rust Build Environment'
description: 'Install Rust toolchain and common tools. Build caching is handled by sccache (configured in .cargo/config.toml + CI workflow).'

inputs:
  install-dioxus:
    description: 'Whether to install Dioxus CLI'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Rust (uses rust-toolchain.toml)
      shell: bash
      run: |
        rustup show
        rustup target add wasm32-unknown-unknown

    - name: Add cargo bin to PATH
      shell: bash
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install cargo-binstall
      shell: bash
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

    - name: Install Dioxus CLI
      if: inputs.install-dioxus == 'true'
      shell: bash
      run: cargo binstall dioxus-cli@0.7.2 --no-confirm --locked
