name: 'Setup macOS Build Environment'
description: 'Install macOS dependencies and configure environment for building bae'

inputs:
  ffmpeg-version:
    description: 'bae-ffmpeg release tag'
    required: false
    default: 'v8.0.1-bae3'

runs:
  using: 'composite'
  steps:
    - name: Install macOS dependencies
      shell: bash
      run: |
        brew install libdiscid libcdio libsodium pkg-config libtorrent-rasterbar boost openssl@3 switchaudio-osx

    - name: Download bae-ffmpeg
      shell: bash
      run: |
        ARCH=$(uname -m)
        FFMPEG_DIR=/opt/bae-ffmpeg
        sudo mkdir -p "$FFMPEG_DIR"
        curl -L "https://github.com/bae-fm/bae-ffmpeg/releases/download/${{ inputs.ffmpeg-version }}/ffmpeg-macos-$ARCH.tar.gz" | \
          sudo tar xz -C "$FFMPEG_DIR"
        echo "FFMPEG_DIR=$FFMPEG_DIR" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$FFMPEG_DIR/lib/pkgconfig" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$FFMPEG_DIR/lib" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=$FFMPEG_DIR/lib" >> $GITHUB_ENV
        echo "BINDGEN_EXTRA_CLANG_ARGS=-I$FFMPEG_DIR/include" >> $GITHUB_ENV
        echo "$FFMPEG_DIR/bin" >> $GITHUB_PATH

    - name: Setup virtual audio device
      shell: bash
      run: |
        SwitchAudioSource -a
        SwitchAudioSource -s "Null Audio Device"
